#現在は対応しないが、将来的に対応する規約の読み込み
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  # Ruby/Railsバージョン指定
  TargetRubyVersion: 2.6.6
  TargetRailsVersion: 5.2.4.3
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'db/schema.rb'
    - !ruby/regexp /old_and_unused\.rb$/

#Rails仕様にする
Rails:
  Enable: true

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false
